# test
baseURL = "http://fightpompe.com/donor2019/"

# staging
# baseURL = "http://adbpublicstg.prod.acquia-sites.com/multimedia/partnership-report2019/"

# live
#baseURL = "https://www.adb.org/multimedia/partnership-report2019/"


languageCode = "en-us"
theme = "donor2019"
summaryLength = 10
title = "Partnership Report 2019"

[params]
  # meta data
  author = "Asian Development Bank (ADB)"
  title = "ADB Partnership Report 2019: Building Strong Partnerships for Shared Progress"
  description = "ADB Strategy 2030 works to eradicate extreme poverty while expanding its vision of a prosperous, inclusive, resilient, and sustainable Asia and the Pacific. Financing partnerships are critical to delivering this vision. The 2019 ADB Partnership Report highlights many exciting and impactful examples of ADB financing partnerships (“cofinancing”) in both the ADB’s sovereign and nonsovereign operations. These examples illustrate how cofinancing partnerships are delivering concrete impacts on the ground, how they are aligned with the ADB Strategy 2030’s seven operational priorities, and how cofinancing amplifies ADB’s private sector operations. It features stories and summaries of how these partnerships have made a significant difference in the lives of the poor."
  keywords = "Sovereign financing partnerships, cofinancing, co-financing, private sector cofinancing, nonsovereign cofinancing, ADB Partnerships Report, ADB Donor Report, development cofinancing, ADB cofinancing operations, strong partnerships, shared progress, ADB Strategy 2030 operational priorities, trust funds, project specific cofinancing, financing partnership facilities"

# Site Menus
[menu]
# Navbar Menus
# [[menu.main]]
#   identifier = "home"
#   name = "Home"
#   url = "/"
#   weight  = 1

# [[menu.main]]
#   identifier = "overview"
#   name = "Overview"
#   url = "/overview/"
#   weight  = 2

[[menu.main]]
  identifier = "data"
  name = "Data"
  url = "/data/"
  weight  = 2

[[menu.main]]
  identifier = "strategy-2030"
  name = "Strategy 2030"
  url = "/strategy-2030/"
  weight  = 3

[[menu.main]]
    identifier = "poverty"
    name = "Poverty"
    url = "/strategy-2030/addressing-remaining-poverty-and-reducing-inequalities/"
    parent = "strategy-2030"
    weight = 31

[[menu.main]]
    identifier = "gender-equality"
    name = "Gender Equality"
    url = "/strategy-2030/gender-equality/"
    parent = "strategy-2030"
    weight = 32

[[menu.main]]
    identifier = "climate-change"
    name = "Climate Change"
    url = "/strategy-2030/climate-change/"
    parent = "strategy-2030"
    weight = 33

[[menu.main]]
    identifier = "livable-cities"
    name = "Livable Cities"
    url = "/strategy-2030/livable-cities/"
    parent = "strategy-2030"
    weight = 34

[[menu.main]]
    identifier = "rural-development"
    name = "Rural Development"
    url = "/strategy-2030/rural-development-and-food-security/"
    parent = "strategy-2030"
    weight = 35

[[menu.main]]
    identifier = "governance"
    name = "Governance"
    url = "/strategy-2030/governance-and-capacity-building/"
    parent = "strategy-2030"
    weight = 36

[[menu.main]]
    identifier = "regional-cooperation-integration"
    name = "Regional Cooperation and Integration"
    url = "/strategy-2030/regional-cooperation-and-integration/"
    parent = "strategy-2030"
    weight = 37

[[menu.main]]
  identifier = "private-sector"
  name = "Private Sector"
  url = "/private-sector/"
  weight  = 4

[[menu.main]]
  identifier = "stories"
  name = "Stories"
  url = "/stories/"
  weight  = 5

[[menu.main]]
  identifier = "partners"
  name = "Partners"
  url = "/partners/"
  weight  = 6

[[menu.main]]
    identifier = "bilateral"
    name = "Bilateral"
    url = "/partners/bilateral/"
    parent = "partners"
    weight = 61

[[menu.main]]
    identifier = "multilateral"
    name = "Multilateral"
    url = "/partners/multilateral/"
    parent = "partners"
    weight = 62

[[menu.main]]
    identifier = "others"
    name = "Others"
    url = "/partners/others/"
    parent = "partners"
    weight = 63

[[menu.main]]
  identifier = "projects"
  name = "Projects"
  url = "/projects/"
  weight  = 7

[[menu.main]]
  identifier = "modalities"
  name = "Modalities"
  url = "/modalities/"
  weight  = 8

[[menu.main]]
    identifier = "project-specific-cofinancing"
    name = "Project-Specific Cofinancing"
    url = "/modalities/project-specific-cofinancing/"
    parent = "modalities"
    weight = 81

[[menu.main]]
    identifier = "global-funds"
    name = "&raquo; Global Funds"
    url = "/modalities/global-funds/"
    parent = "modalities"
    weight = 82

[[menu.main]]
    identifier = "trust-funds"
    name = "Trust Funds"
    url = "/modalities/trust-funds/"
    parent = "modalities"
    weight = 83

[[menu.main]]
    identifier = "single-partner-trust-funds"
    name = "&raquo; Single-Partner Trust Funds"
    url = "/modalities/trust-funds/single-partner-trust-funds/"
    parent = "modalities"
    weight = 84

[[menu.main]]
    identifier = "multi-partner-trust-funds"
    name = "&raquo; Multi-Partner Trust Funds"
    url = "/modalities/trust-funds/multi-partner-trust-funds/"
    parent = "modalities"
    weight = 85

[[menu.main]]
    identifier = "financing-partnership-facilities"
    name = "&raquo; Financing Partnership Facilities"
    url = "/modalities/financing-partnership-facilities/"
    parent = "modalities"
    weight = 86

[[menu.main]]
    identifier = "partnership-framework-arrangements"
    name = "Partnership Framework Arrangements"
    url = "/modalities/partnership-framework-arrangements/"
    parent = "modalities"
    weight = 86


  [markup]
  [markup.goldmark]
    [markup.goldmark.extensions]
      definitionList = true
      footnote = true
      linkify = true
      strikethrough = true
      table = true
      taskList = true
      typographer = true
    [markup.goldmark.parser]
      attribute = true
      autoHeadingID = true
      autoHeadingIDType = "github"
    [markup.goldmark.renderer]
      hardWraps = false
      unsafe = true
      xhtml = false



