baseURL = "http://fightpompe.com/donor2019/"
languageCode = "en-us"
theme = "donor2019"
summaryLength = 10
title = "Partnership Report 2019"

[params]
  # meta data
  author = "Juan"
  description = "This is meta description"

# Site Menus
[menu]
# Navbar Menus
# [[menu.main]]
#   identifier = "home"
#   name = "Home"
#   url = "/"
#   weight  = 1

[[menu.main]]
  identifier = "overview"
  name = "Overview"
  url = "/overview/"
  weight  = 2

[[menu.main]]
  identifier = "data"
  name = "Data"
  url = "/data/"
  weight  = 3

[[menu.main]]
  identifier = "strategy-2030"
  name = "Strategy 2030"
  url = "/strategy-2030/"
  weight  = 4

[[menu.main]]
    identifier = "poverty"
    name = "Poverty"
    url = "/strategy-2030/addressing-remaining-poverty-and-reducing-inequalities/"
    parent = "strategy-2030"
    weight = 41

[[menu.main]]
    identifier = "gender-equality"
    name = "Gender Equality"
    url = "/strategy-2030/gender-equality/"
    parent = "strategy-2030"
    weight = 42

[[menu.main]]
    identifier = "climate-change"
    name = "Climate Change"
    url = "/strategy-2030/climate-change/"
    parent = "strategy-2030"
    weight = 43

[[menu.main]]
    identifier = "livable-cities"
    name = "Livable Cities"
    url = "/strategy-2030/livable-cities/"
    parent = "strategy-2030"
    weight = 44

[[menu.main]]
    identifier = "rural-development"
    name = "Rural Development"
    url = "/strategy-2030/rural-development-and-food-security/"
    parent = "strategy-2030"
    weight = 45

[[menu.main]]
    identifier = "governance"
    name = "Governance"
    url = "/strategy-2030/governance-and-capacity-building/"
    parent = "strategy-2030"
    weight = 46

[[menu.main]]
    identifier = "regional-cooperation-integration"
    name = "Regional Cooperation and Integration"
    url = "/strategy-2030/regional-cooperation-and-integration/"
    parent = "strategy-2030"
    weight = 47

[[menu.main]]
  identifier = "stories"
  name = "Stories"
  url = "/stories/"
  weight  = 5

[[menu.main]]
  identifier = "partners"
  name = "Partners"
  url = "/partners/"
  weight  = 6

[[menu.main]]
    identifier = "bilateral"
    name = "Bilateral"
    url = "/partners/bilateral/"
    parent = "partners"
    weight = 61

[[menu.main]]
    identifier = "multilateral"
    name = "Multilateral"
    url = "/partners/multilateral/"
    parent = "partners"
    weight = 62

[[menu.main]]
    identifier = "others"
    name = "Others"
    url = "/partners/others/"
    parent = "partners"
    weight = 63

[[menu.main]]
  identifier = "projects"
  name = "Projects"
  url = "/projects/"
  weight  = 7

[[menu.main]]
  identifier = "modalities"
  name = "Modalities"
  url = "/modalities/"
  weight  = 8

[[menu.main]]
    identifier = "project-specific-cofinancing"
    name = "Project-Specific Cofinancing"
    url = "/modalities/project-specific-cofinancing/"
    parent = "modalities"
    weight = 81

[[menu.main]]
    identifier = "global-funds"
    name = "&raquo; Global Funds"
    url = "/modalities/global-funds/"
    parent = "modalities"
    weight = 82

[[menu.main]]
    identifier = "trust-funds"
    name = "Trust Funds"
    url = "/modalities/trust-funds/"
    parent = "modalities"
    weight = 83

[[menu.main]]
    identifier = "single-partner-trust-funds"
    name = "&raquo; Single-Partner Trust Funds"
    url = "/modalities/trust-funds/single-partner-trust-funds/"
    parent = "modalities"
    weight = 84

[[menu.main]]
    identifier = "multi-partner-trust-funds"
    name = "&raquo; Multi-Partner Trust Funds"
    url = "/modalities/trust-funds/multi-partner-trust-funds/"
    parent = "modalities"
    weight = 85

[[menu.main]]
    identifier = "financing-partnership-facilities"
    name = "&raquo; Financing Partnership Facilities"
    url = "/modalities/financing-partnership-facilities/"
    parent = "modalities"
    weight = 86

[[menu.main]]
    identifier = "partnership-framework-arrangements"
    name = "Partnership Framework Arrangements"
    url = "/modalities/partnership-framework-arrangements/"
    parent = "modalities"
    weight = 86

[[menu.main]]
  identifier = "nonsovereign-cofinancing"
  name = "Nonsovereign"
  url = "/nonsovereign-cofinancing/"
  weight  = 9


  [markup]
  [markup.goldmark]
    [markup.goldmark.extensions]
      definitionList = true
      footnote = true
      linkify = true
      strikethrough = true
      table = true
      taskList = true
      typographer = true
    [markup.goldmark.parser]
      attribute = true
      autoHeadingID = true
      autoHeadingIDType = "github"
    [markup.goldmark.renderer]
      hardWraps = false
      unsafe = true
      xhtml = false



