baseURL = "http://fightpompe.com/donor2019/"
languageCode = "en-us"
theme = "donor2019"
summaryLength = 10

[params]
  # meta data
  title = "Donor Report 2019"
  author = "Juan"
  description = "This is meta description"